version: "3.9"

networks:
  demo-server:
    driver: bridge

services:
  app-2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - demo-server
    ports:
      - 6000:6000
